### ISSUE TITLE
nokogiri version is too old

### ISSUE THREAD

**Issue by yegor256** [pedrocarrico/public_ip#5]
Do you really need `~>1.8.1`? See: https://github.com/pedrocarrico/public_ip/blob/master/public_ip.gemspec#L32 How about specifying it like `=>1.8`? I can't use your library because I'm with Nokogiri 1.10+. Please, fix. I'd love to use your gem! :)

**Comment by yegor256** [comment]
@pedrocarrico please help

**Comment by pedrocarrico** [comment]
@yegor256 nokogiri updated to the latest version in version 0.2.1

https://rubygems.org/gems/public_ip/versions/0.2.1

Thanks

**Comment by yegor256** [comment]
@pedrocarrico thanks!

**Comment by pedrocarrico** [comment]
Anytime @yegor256 , glad you're using public_ip.

If you need any other feature feel free to ping me.
